version: 2

build:
  jobs:
    post_checkout:
      - pip install uv

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs